version: '3.8'

services:
  db:
   container_name: postgres_container
   image: postgres
   restart: always
   environment:
     POSTGRES_DB: postgres_db
     POSTGRES_USER: admin
     POSTGRES_PASSWORD: secret
     PGDATA: /var/lib/postgresql/data
   ports:
     - "5432:5432"
   volumes:
     - db-data:/var/lib/postgresql/data
  pgadmin:
   container_name: pgadmin4_container
   image: dpage/pgadmin4:6.16
   restart: always
   environment:
     PGADMIN_DEFAULT_EMAIL: admin@admin.com
     PGADMIN_DEFAULT_PASSWORD: secret
     PGADMIN_LISTEN_PORT: 80
   ports:
     - "8050:80"
   volumes:
     - pgadmin-data:/var/lib/pgadmin
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    networks:
      - default
    ports:
    - "8060:80"
volumes:
  db-data:
  pgadmin-data: